name: Testing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Google App Engine
        uses: claudiuri/deploy-gae-action@master
        with:
          service-account:  ${{ secrets.SERVICE_ACCOUNT }}
          project-id: ${{ secrets.PROJECT_ID }}
