name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy --quiet

      # check app
      - name: Check if app is reachable
        uses: fjogeleit/http-request-action@master
        with:
          url: https://${{ secrets.PROJECT_ID }}.oa.r.appspot.com/now
          method: GET
