name: Unit Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.8', '3.7']
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0

      - name: Python Pylin GitHub Action
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pytest -v
