name: Validator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.8', '3.7']
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0

      - name: doockerfile-validator
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'
